---
title: "Regression Analysis"
author: "Stephan Huber"
date: "24 11 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Table of Content**

[1. Motivation](#motivation)

[2. Regression Model](#regression)

[3. Regression Analysis in R](#regression-in-R)


# Sources:

Have a look at the following sources:
 
+ [Constantin Colonescu: Principles of Econometrics with R](https://bookdown.org/ccolonescu/RPoE4/)
+ [Hanck et al: Introduction to Econometrics with R](https://www.econometrics-with-r.org/index.html)
+ [Wikipedia: Regression Analysis](https://en.wikipedia.org/wiki/Regression_analysis)
+ [Julian J. Faraway: Practical Regression and Anova using R](https://cran.r-project.org/doc/contrib/Faraway-PRA.pdf)

Interesting bits of information:

+ [Linear Equation Vs Non-linear equation](https://findanyanswer.com/goto/117180)
+ [Short questions about regression analysis](https://findanyanswer.com/how-regression-is-important-in-economic-analysis)
+ [7 Classical Assumptions of Ordinary Least Squares (OLS)](https://statisticsbyjim.com/regression/ols-linear-regression-assumptions/)
+ [The Gauss-Markov Theorem and BLUE OLS Coefficient Estimates](https://statisticsbyjim.com/regression/gauss-markov-theorem-ols-blue/)
+ [Statistics by Jim](https://statisticsbyjim.com/regression/)
+ [Violation of the classical assumptions](http://www.staff.city.ac.uk/~sm340/MSCQTRP/Lecture1term2Violations.pdf)

Some tutorials:

+ [Tamas Nagy: Linear regression models](https://docs.google.com/presentation/d/1ZFg1atnmFx-Tx_giMFBQh2TXHQvveC4dM4eZ8cZePQg/edit?usp=sharing)
+ [Other stuff from T. Nagy](https://osf.io/4fntj/)
+ [Regression 101: Understanding business flows with OLS regression in R](https://novustat.com/statistik-blog/ols-regression-101.html)
+ [Complete Introduction to Linear Regression in R](https://www.machinelearningplus.com/machine-learning/complete-introduction-linear-regression-r/)
+ [Linear Regression in R](https://www.datacamp.com/community/tutorials/linear-regression-R)

## Learning Objectives:
Students will ...

+ ... get known to the ability of a regression analysis to estimate the relationships between a dependent variable and multiple independent variables.
+ ... be introduced to the properties of the ordinary least squared estimation method.
+ ... learn the seven assumptions of the regression model.
+ ... be introduced to the consequences if  assumptions of a regression model are violated.
+ ... learn how the programming language R can be applied to execute a regression analysis.



# Motivation {#motivation}

---

# Regression model {#regression}

### Simple linear regression

### Multiple linear regression 

## Ordinary least squares (OLS)

### The seven classical OLS assumption

### BLUE

## Violations of the assumptions

### Omitted variable bias and misspecification

### Korelation does not imply causation

### Simpsons paradox

### Heteroskedasticity

## $R^2$: the coefficient of determination

---


# Regression Analysis in R {#regression-in-R}

## How to *run* a regression in R

## How to *test for omitted variable bias*

[Omitted Variable Bias](https://www.econometrics-with-r.org/6-1-omitted-variable-bias.html)


# Excercise
  


